version: '2'
services:
  api-gateway: 
    build:
      context: ./api-gateway
    container_name: api-gateway
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:4000
      - 3000:3000
      - 443:443
      - 80:80
    depends_on: 
      - web-api
      - web-app

  web-api:
    build:
      context: ./back-end/
    command: npm start
    volumes:
      - ./back-end/:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
  web-app:
    build:
      context: ./front-end/
    command: npm start
    volumes:
      - ./front-end/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - web-api
    environment:
      - NODE_ENV=development
      - API_PORT=3000
      - API_HOSTNAME=localhost
      - HTTP_PROTOCOL=https  